sample_rate: 44100
sources: ["drums", "bass", "vocals", "other"]

model:
  num_layers: 6
  initial_channel: 64
dataset:
  train:
    chunk_duration: 11
  valid:
    chunk_duration: 300
optimizer:
  lr: 0.0003
quantizer:
  penalty: 0.0003
criterion:
  method: "L1LossWithTrimming"
  kwargs:

batch_size: 64
validation_period: 1
