name: demucs_clone
channels:
  - defaults
dependencies:
  - pip=21.1.3
  - python=3.9.5
  - pip:
      - musdb==0.4.0
      - pyyaml==5.4.1
      - torch==1.9.0
      - torchaudio==0.9.0
      - tensorboard==2.5.0
      - museval==0.4.0
      - diffq==0.1.1